name: Cypress - Every 15 minutes (CRON)

on:
  schedule:
    - cron: "*/15 01-03 * * *" # Každých 15 minut mezi 19:00 a 21:59

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
