name: Cypress Tests Filtering - Tag

on:
  workflow_dispatch: # Ruční spouštění přes GitHub UI

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress smoke tests
        run: npx cypress run --env grepTags=@smoke
